name: ecommerce
description: An E-commerce app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  dropdown_search: ^0.6.1
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  firebase_storage: ^8.1.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.6
  google_sign_in: ^5.0.2
  http: ^0.13.3
  image_picker: ^0.7.5+3
  momo_vn: ^1.0.4
  provider: ^5.0.0
  random_string: ^2.2.0-nullsafety
  shared_preferences: ^2.0.5
  timeago: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
