name: ecommerce
description: An E-commerce app.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.12.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    firebase_core: ^1.0.3
    firebase_auth: ^1.1.0
    cloud_firestore: ^1.0.5
    google_sign_in: ^5.0.2

    shared_preferences: "^2.0.5"
    random_string: ^2.2.0-nullsafety

    cupertino_icons: "^1.0.2"
    flutter_svg: ^0.21.0+1
    flutter_spinkit: ^5.0.0
    momo_vn:
        path: ../
    fluttertoast: ^8.0.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    flutter_launcher_icons: "^0.9.0"

flutter_icons:
    android: true
    ios: true
    image_path: "assets/logo.png"

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/icons/

    fonts:
        - family: Muli
          fonts:
              - asset: assets/fonts/muli/Muli.ttf
              - asset: assets/fonts/muli/Muli-Bold.ttf
                weight: 700
              - asset: assets/fonts/muli/Muli-Light.ttf
                weight: 300
    #
